# Generated by Django 5.2.7 on 2025-11-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_time_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_time_out',
            field=models.BooleanField(default=False),
        ),
    ]
