# Generated by Django 5.2.5 on 2025-10-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_role_profile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credential_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
