# Generated by Django 5.2.5 on 2025-10-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_credential_id_profile_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sign_count',
        ),
    ]
