# Generated by Django 5.2.5 on 2025-10-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_profile_credential_id_remove_profile_face_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='schoolId',
        ),
    ]
